-- CreateEnum
CREATE TYPE "AiAgentGender" AS ENUM ('FEMALE', 'MALE');

-- AlterTable
ALTER TABLE "tenant_settings" ADD COLUMN "ai_agent_gender" "AiAgentGender" NOT NULL DEFAULT 'FEMALE';

-- AuditAction AI suggest events
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AI_SUGGEST_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AI_SUGGEST_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AI_SUGGEST_EDITED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AI_SUGGEST_REJECTED';
